### ISSUE TITLE
Issue with 'Radiance Glass Material by Single Value' node

### ISSUE THREAD

**Issue by teabaker** [ladybug-tools/honeybee-plus#45]
Hi!

I am having problems with the 'Radiance Glass Material by Single Value' node in my daylight script. It appears that no light is being transmitted through the glass surfaces. I am using a simple model with 3 identical windows.

If I define the Radiance Material by the Surface Type (5.0: Window), it works fine - see below for comparison of results.

Is this an error, or am I doing something wrong?

Thanks!

Case 1: defining using glass material node
![15](https://cloud.githubusercontent.com/assets/25978191/23757370/eb0cbd26-04e6-11e7-8e58-1055a3cabd52.png)

Case 2: defining by surface type
![16](https://cloud.githubusercontent.com/assets/25978191/23757379/f3c68e88-04e6-11e7-8b64-8e47dd151665.png)

**Comment by mostaphaRoudsari** [comment]
@teabaker thanks for reporting this. This is a bug but it is fixed in the new library. For now we can use a little bit of python to assign the new materials outside the node.

![image](https://cloud.githubusercontent.com/assets/2915573/23798167/4b006284-0571-11e7-9db5-b61cabe7a8c0.png)

Sorry for making you to use Python for stuff like this that should work by default. Again since we will have a new release which has major changes I'm trying not to spend a lot of time on the current version. These will be all work as expected in the next release.

**Comment by teabaker** [comment]
Totally understandable. Thanks for taking the time to provide a temporary solution!

**Comment by mostaphaRoudsari** [comment]
This is fixed in the new version as it's taking us so long to release the new plugin.

![image](https://cloud.githubusercontent.com/assets/2915573/26524409/a3f9b4e6-42ff-11e7-8636-d2427beb6097.png)
