### ISSUE TITLE
Honeybee in Dynamo is not running 

### ISSUE THREAD

**Issue by Mahamiho** [ladybug-tools/honeybee-plus#55]
Hey @mostaphaRoudsari 
I am experiencing some problems in running Honeybee in Dynamo on my computer despite that the same file runs on another computer. I dont get any errors I just get an empty list, and honeybee in grasshopper is working fine. I had an issue with the firewall on my computer, but I dont think it is the case since it is working properly in Grasshopper now. The dynamo version is 1.3, and I am attaching the file generated from Honeybee, I can see an error file but I dont understand what is the problem, Thanks alot,
![error no simulation](https://cloud.githubusercontent.com/assets/26859104/26527668/be99f682-4398-11e7-8775-373f534fd5f7.PNG)
[MSH.zip](https://github.com/ladybug-tools/honeybee-plus/files/1034071/MSH.zip)

**Comment by mostaphaRoudsari** [comment]
Hi @Mahamiho, It runs fine on my machine but I can see the error message inside the folder (Thanks for sharing the folder BTW).

Since everything looks fine in the folder I assume the error happens because `gensky` command doesn't run successfully and that's because radiance is not added to system path. Add radiance\bin to system path and try again and I assume it will run fine. Feel free to re-open the issue if it didn't solve the problem.
