### ISSUE TITLE
Showing Honeybee Results As Colores Surface in Revit

### ISSUE THREAD

**Issue by SamDehghani** [ladybug-tools/honeybee-plus#57]
Hi There,
Trying to show Honeybee results in Revit as colored surface seems to be pretty successful, however I encountered a strange issue. When the rooms are rectangular the output polygons of "Generate Test Points" works fine.
![test for github](https://user-images.githubusercontent.com/28707495/26947381-cae88256-4ca7-11e7-9cc0-75395e58533a.PNG)
When the room are somehow more complicated the polygons fail to follow the rooms outline. Some polygon turn into irregular shapes.
![test wrong](https://user-images.githubusercontent.com/28707495/26947460-0875e6c2-4ca8-11e7-8d80-990e493bfa5e.PNG)
![test wrong 01](https://user-images.githubusercontent.com/28707495/26947463-10170078-4ca8-11e7-873d-c2765dd64133.PNG)

Did I do anything wrong? Should I adjust something in a different way?
Thanks in advance,

**Comment by mostaphaRoudsari** [comment]
Hi @SamDehghani, You're not doing anything wrong. It's because how Honeybee creates the test surfaces. Since Dynamo doesn't have a good meshing library to help with edge cases I create a grid of squares and then check and remove the squares that any of the points are outside the boundary. If you try a smaller grid size it should cover your case here but the eventual solution is to write a more sophisticated algorithm to generate the test grid.

**Comment by SamDehghani** [comment]
Hi @mostaphaRoudsari ,
Thank you very much.

**Comment by mostaphaRoudsari** [comment]
We can close this for now. Here is the [example files](http://hydrashare.github.io/hydra/?keywords=samDehghani).

**Comment by andreameneg** [comment]
Dear @SamDehghani , thanks for your script!

Would it be possible to update your sample with the new releases of Honeybee and Ladybug? I am having some issues with your workflow. In particular with Leged Setting and Colored Surfece Display for HB.

Thanks
Andrea
